### ISSUE TITLE
Pre-trained Model

### ISSUE THREAD

**Issue by hologerry** [suikei-wong/Facial-Attributes-Classification#1]
Could you please provide the pre-trained model?

**Comment by suikei-wong** [comment]
> Could you please provide the pre-trained model?

Hi, sorry I did not keep the original best pre-trained best model. But I can provide the Jupyter Notebook running version of the whole experiments: [Run.ipynb](https://colab.research.google.com/drive/1SHZd4gX7NWN5VhfXfAVx8KbxzfupAPEd?usp=sharing). You can run it to get the model file (model_checkpoint.pth) with **aligned** CelebA dataset. It won't be too long to train this model using GPU and the final model is around 30MB. ;)

**Comment by hologerry** [comment]
OK, Thanks!

**Comment by MrCabss69** [comment]
Thanks!
